### ISSUE TITLE
Add support for setTrace Notification

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#103]
This is used by LS client to set the tracing level on the server.
```
Failed to handle notification $/setTrace: Object(value='verbose')
Traceback (most recent call last):
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 279, in _get_handler
    return self.fm.builtin_features[feature_name]
KeyError: '$/setTrace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 282, in _get_handler
    return self.fm.features[feature_name]
KeyError: '$/setTrace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 306, in _handle_notification
    handler = self._get_handler(method_name)
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 284, in _get_handler
    raise JsonRpcMethodNotFound.of(feature_name)
pygls.exceptions.JsonRpcMethodNotFound
```

**Comment by pappasam** [comment]
Hmm, this may be worth filing with `pygls` under `3.16` support (I think `$/setTrace` was introduced in `3.16`). The [most recent release](https://github.com/openlawlibrary/pygls/pull/139) FINALLY (supposedly) supports everything from 3.15. We might consider writing a patch / dummy function at least not raise an error.

That said, I'm not sure how I'd go about addressing this effectively on my end since I don't use VSCode and will have a hard time knowing whether an implementation provides the intended behavior / workarounds.

**Comment by karthiknadig** [comment]
Opened https://github.com/openlawlibrary/pygls/issues/162

**Comment by pappasam** [comment]
I believe this has been resolved for a while, see https://github.com/openlawlibrary/pygls/blob/720da69128654fa9c98f0e917451eef76cc9a0d8/pygls/protocol.py#L654
