### ISSUE TITLE
renaming package fails with unknown workspace edit error

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#134]
```
Unknown workspace edit change received:
{
    "oldUri": "file:///c:/GIT/repro/renaming/somepackage",
    "newUri": "file:///c:/GIT/repro/renaming/package1",
    "options": {
        "overwrite": true,
        "ignoreIfExists": true
    }
}
```

Repro steps:
1. Create this package layout
![image](https://user-images.githubusercontent.com/3840081/115483966-b085e300-a206-11eb-8c7a-fcec393ad385.png)

somemodule.py: contents
```py
def do_something():
    print('something')
```
myscript.py: contents
```py
from somepackage.somemodule import do_something

def run():
    do_something()

run()
```
3. Place cursor on `somepackage` in `myscript.py`, and rename it.

LSP messages trace:
```

[Trace - 6:29:50 PM] Sending request 'textDocument/rename - (8)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/GIT/repro/renaming/myscript.py"
    },
    "position": {
        "line": 0,
        "character": 13
    },
    "newName": "package1"
}


[Trace - 6:29:50 PM] Received response 'textDocument/rename - (8)' in 8ms.
Result: {
    "documentChanges": [
        {
            "textDocument": {
                "uri": "file:///c:/GIT/repro/renaming/myscript.py",
                "version": 0
            },
            "edits": [
                {
                    "range": {
                        "start": {
                            "line": 0,
                            "character": 5
                        },
                        "end": {
                            "line": 0,
                            "character": 9
                        }
                    },
                    "newText": ""
                },
                {
                    "range": {
                        "start": {
                            "line": 0,
                            "character": 16
                        },
                        "end": {
                            "line": 0,
                            "character": 16
                        }
                    },
                    "newText": "1"
                },
                {
                    "range": {
                        "start": {
                            "line": 0,
                            "character": 47
                        },
                        "end": {
                            "line": 0,
                            "character": 47
                        }
                    },
                    "newText": "\r"
                },
                {
                    "range": {
                        "start": {
                            "line": 1,
                            "character": 0
                        },
                        "end": {
                            "line": 1,
                            "character": 0
                        }
                    },
                    "newText": "\r"
                },
                {
                    "range": {
                        "start": {
                            "line": 2,
                            "character": 10
                        },
                        "end": {
                            "line": 2,
                            "character": 10
                        }
                    },
                    "newText": "\r"
                },
                {
                    "range": {
                        "start": {
                            "line": 3,
                            "character": 18
                        },
                        "end": {
                            "line": 3,
                            "character": 18
                        }
                    },
                    "newText": "\r"
                },
                {
                    "range": {
                        "start": {
                            "line": 4,
                            "character": 0
                        },
                        "end": {
                            "line": 4,
                            "character": 0
                        }
                    },
                    "newText": "\r"
                },
                {
                    "range": {
                        "start": {
                            "line": 5,
                            "character": 0
                        },
                        "end": {
                            "line": 5,
                            "character": 0
                        }
                    },
                    "newText": "\r"
                }
            ]
        },
        {
            "oldUri": "file:///c:/GIT/repro/renaming/somepackage",
            "newUri": "file:///c:/GIT/repro/renaming/package1",
            "options": {
                "overwrite": true,
                "ignoreIfExists": true
            }
        }
    ]
}

```
Proably just missing edit kind:

```

        {
kind: 'rename'
            "oldUri": "file:///c:/GIT/repro/renaming/somepackage",
            "newUri": "file:///c:/GIT/repro/renaming/package1",
            "options": {
                "overwrite": true,
                "ignoreIfExists": true
            }
        }
```

**Comment by karthiknadig** [comment]
Filed https://github.com/openlawlibrary/pygls/issues/176 on `pygls` to fix this.

**Comment by pappasam** [comment]
@karthiknadig has this been resolved with the latest pygls release?

**Comment by karthiknadig** [comment]
I have not had an opportunity to test this. I also think we need to add a test case for this since this is a special case (i.e., it generates an different protocol message)

**Comment by karthiknadig** [comment]
So it looks like we need a fix in `jedi-language-server`, we will need to pass `kind` to RenameFile here:
https://github.com/pappasam/jedi-language-server/blob/b408d6852921c98f5bbaf9942bbbf40f4cd30f07/jedi_language_server/text_edit_utils.py#L60-L66

With the above issue fixed, it looks like `jedi` itself might need a fix, trying to rename a namespace package leads to this error. The rename works fine if it has a `__init__.py`
![image](https://user-images.githubusercontent.com/3840081/119252271-1942e100-bb60-11eb-9ea4-9f4fbe4cef44.png)

```
[Trace - 12:40:43 AM] Sending request 'textDocument/rename - (123)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/GIT/repro/demo/renametest/demo.py"
    },
    "position": {
        "line": 0,
        "character": 11
    },
    "newName": "newname"
}


ERROR:pygls.protocol:Failed to handle request 123 textDocument/rename work_done_token=None text_document=TextDocumentIdentifier(uri='file:///c%3A/GIT/repro/demo/renametest/demo.py') position=0:11 new_name='newname'
Traceback (most recent call last):
  File "c:\Users\Karthik Nadig\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\jedilsp\pygls\protocol.py", line 342, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "c:\Users\Karthik Nadig\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\jedilsp\pygls\protocol.py", line 271, in _execute_request
    method_name, method_type, msg_id, handler(params))
  File "c:\Users\Karthik Nadig\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\jedilsp\jedi_language_server\server.py", line 433, in rename
    refactoring = jedi_script.rename(
  File "c:\Users\Karthik Nadig\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\jedilsp\jedi\api\__init__.py", line 578, in rename
    return refactoring.rename(self._inference_state, definitions, new_name)
  File "c:\Users\Karthik Nadig\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\jedilsp\jedi\api\refactoring\__init__.py", line 146, in rename
    file_renames.add(_calculate_rename(p, new_name))
  File "c:\Users\Karthik Nadig\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\jedilsp\jedi\api\refactoring\__init__.py", line 129, in _calculate_rename
    dir_ = path.parent
AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by pappasam** [comment]
I'll look into this later this week!

**Comment by anu-ka** [comment]
@pappasam I have created a fix for this. Please have a look.
