### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by wy-z** [pappasam/jedi-language-server#21]
First of all, thank you for your great work~
And the language server always crashes in recent versions.

#### Traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/jedi-language-server", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi_language_server/cli.py", line 17, in cli
    SERVER.start_io()
  File "/usr/local/lib/python3.7/site-packages/pygls/server.py", line 179, in start_io
    self.lsp.data_received))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/pygls/server.py", line 69, in aio_readline
    proxy(b''.join(message))
  File "/usr/local/lib/python3.7/site-packages/pygls/protocol.py", line 445, in data_received
    object_hook=deserialize_message))
  File "/usr/local/lib/python3.7/site-packages/pygls/protocol.py", line 370, in _procedure_handler
    self._handle_response(message.id, message.result, message.error)
  File "/usr/local/lib/python3.7/site-packages/pygls/protocol.py", line 349, in _handle_response
    future.set_exception(JsonRpcException.from_dict(error))
  File "/usr/local/lib/python3.7/site-packages/pygls/exceptions.py", line 44, in from_dict
    if exc_class.supports_code(error['code']):
TypeError: tuple indices must be integers or slices, not str
```

#### Log
![image](https://user-images.githubusercontent.com/4213483/81261945-8bd54180-906f-11ea-9504-19377c043445.png)

#### Version Info
```
jedi                 0.17.0
jedi-language-server 0.7.2
pygls                0.9.0
```

**Comment by pappasam** [comment]
Would you please upgrade `jedi-language-server` to the latest version (`0.12.3` at this time) and let me know if the problem persists?

`pip install -U jedi-language-server`, or `pipx upgrade jedi-language-server` if you're using [pipx](https://github.com/pipxproject/pipx).

Also, based on your logs, I assume you're using [vim-lsp](https://github.com/prabirshrestha/vim-lsp)? That LSP may not support dynamic registration. I've fixed issues related to this in the latest version of this language server. See https://github.com/pappasam/jedi-language-server/issues/15

**Comment by wy-z** [comment]
This problem also exists in `0.12.3' but not in `0.6.1'. @pappasam

**Comment by pappasam** [comment]
Are the logs from 0.12.3 different? If yes, can you please send them to me?

I have some guesses, I'll try get a new version pushed later today and ask you to test it out then

**Comment by wy-z** [comment]
The logs are the same, thanks again.

**Comment by pappasam** [comment]
Please try the latest version (0.13.0) and let me know if the problem persists for you?

**Comment by wy-z** [comment]
Uh...the language server initialized failed.
![image](https://user-images.githubusercontent.com/4213483/81365183-0d81a980-911a-11ea-8cbe-ded731c2f04e.png)
![image](https://user-images.githubusercontent.com/4213483/81365205-1a060200-911a-11ea-8c40-20c03e26953d.png)

**Comment by pappasam** [comment]
Awesome, that error message is clear, that means there’s a documentation issue with pygls. Almost there, I’ll release a slightly more tolerant version tomorrow morning!

**Comment by pappasam** [comment]
@wy-z please try version 0.13.1 when you get a chance and let me know if that fixes the issue!

**Comment by wy-z** [comment]
`0.13.1` is working great for me, thanks! @pappasam
