### ISSUE TITLE
Got no definition for e.g. os.abort()

### ISSUE THREAD

**Issue by SebastianBolte** [pappasam/jedi-language-server#212]
If I try to get a definition for os.abort() I got as result null: 
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 2, "result": null}

The completion for os module is working:
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 3, "result": {"isIncomplete": false, "items": [{"label": "abc", "kind": 9, "sortText": "v000", "filterText": "abc", "insertText": "abc", "insertTextFormat": 1}, {"label": "abort", "kind": 3, "sortText": "v001", "filterText": "abort", "insertText": "abort()$0", "insertTextFormat": 2}, {"label": "access", "kind": 3, ....

What could be the reason that I got null as answer when requesting definition?

**Comment by pappasam** [comment]
There is no definition to jump to because `os.abort` is a builtin function. Run the following code in a Python interpreter:

```python
>>> import os
>>> import inspect
>>> inspect.getsource(os.abort)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    inspect.getsource(os.abort)
  File "/home/sroeca/.asdf/installs/python/3.10.4/lib/python3.10/inspect.py", line 1147, in getsource
    lines, lnum = getsourcelines(object)
  File "/home/sroeca/.asdf/installs/python/3.10.4/lib/python3.10/inspect.py", line 1129, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/sroeca/.asdf/installs/python/3.10.4/lib/python3.10/inspect.py", line 940, in findsource
    file = getsourcefile(object)
  File "/home/sroeca/.asdf/installs/python/3.10.4/lib/python3.10/inspect.py", line 817, in getsourcefile
    filename = getfile(object)
  File "/home/sroeca/.asdf/installs/python/3.10.4/lib/python3.10/inspect.py", line 797, in getfile
    raise TypeError('module, class, method, function, traceback, frame, or '
TypeError: module, class, method, function, traceback, frame, or code object was expected, got builtin_function_or_method
```
