### ISSUE TITLE
It doesn't work with lsprotocol==2023.0.0a0

### ISSUE THREAD

**Issue by AiOO** [pappasam/jedi-language-server#261]
# Background

1. I'm using [coc-jedi](https://github.com/pappasam/coc-jedi) to use jedi-language-server
2. When initializing coc-jedi in Vim, I got an error about jedi-language-server not starting.
```
[coc.nvim] jedi: installing jedi-language-server==0.40.0 in "/Users/ahnkiwook/.config/coc/extensions/node_modules/coc-jedi/.venv"
[coc.nvim] jedi: installed jedi-language-server==0.40.0
[coc.nvim] Unhandled response error -32097 from language server: Pending response rejected since connection got disposed
[coc.nvim] jedi-language-server client: couldn't create connection to server.
```
3. I entered virtual environment specified above meesage.
4. When I run `jedi-language-server`, I get the error message below:
```
(coc-jedi) ~/.config/coc/extensions/node_modules/coc-jedi/.venv ❯ jedi-language-server
Traceback (most recent call last):
  File "/Users/ahnkiwook/.config/coc/extensions/node_modules/coc-jedi/.venv/bin/jedi-language-server", line 5, in <module>
    from jedi_language_server.cli import cli
  File "/Users/ahnkiwook/.config/coc/extensions/node_modules/coc-jedi/.venv/lib/python3.9/site-packages/jedi_language_server/cli.py", line 8, in <module>
    from .server import SERVER
  File "/Users/ahnkiwook/.config/coc/extensions/node_modules/coc-jedi/.venv/lib/python3.9/site-packages/jedi_language_server/server.py", line 68, in <module>
    from pygls.protocol import LanguageServerProtocol, lsp_method
  File "/Users/ahnkiwook/.config/coc/extensions/node_modules/coc-jedi/.venv/lib/python3.9/site-packages/pygls/protocol.py", line 56, in <module>
    from lsprotocol.types import (
ImportError: cannot import name 'WorkspaceConfigurationParams' from 'lsprotocol.types' (/Users/ahnkiwook/.config/coc/extensions/node_modules/coc-jedi/.venv/lib/python3.9/site-packages/lsprotocol/types.py)
``` 
6. From my search, lsprotocol 2023.0.0a0 is [released](https://github.com/microsoft/lsprotocol/releases/tag/2023.0.0a0) 5 hours ago.
7. Running `pip install lsprotocol==2022.0.0a10` is resolve problem.

# Conclusion

An update to the lsprotocol library seems to have caused a dependency issue with the jedi-language-server library.

**Comment by rudenkornk** [comment]
Same issue, I am installing jedi using Mason on neovim.

**Comment by polyzen** [comment]
Resolved with https://github.com/microsoft/lsprotocol/releases/tag/2023.0.0a1

**Comment by AiOO** [comment]
Thanks for quick response. I'm going to close this issue. :)
