### ISSUE TITLE
Exits Immediately on Python 3.12 alpha

### ISSUE THREAD

**Issue by Starz0r** [pappasam/jedi-language-server#263]
Perhaps it's too early to report an issue like this, but just in case you're able to get a handle on it before 3.12 drops, I've decided to report this anyway.

OS: Windows 10 22H2
Python: 3.12.0a6
JLS: 0.40.0, installed through pipx w/ pyenv

```$> jedi-language-server
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "~\.local\bin\jedi-language-server.exe\__main__.py", line 4, in <module>
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\jedi_language_server\cli.py", line 7, in <module>
    from .server import SERVER
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\jedi_language_server\server.py", line 15, in <module>
    from pygls.lsp.methods import (
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\pydantic\main.py", line 369, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\.local\pipx\venvs\jedi-language-server\Lib\site-packages\pydantic\utils.py", line 231, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "~\.pyenv\pyenv-win\versions\3.12.0a6\Lib\inspect.py", line 2734, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
```

**Comment by dimbleby** [comment]
looks like you've made a mess of your installation somehow.  jedi-language-server 0.40.0 relies on pygls >= 1.0.0, which no longer includes the code that is in your stack.

**Comment by Starz0r** [comment]
You're absolutely right. It looks like pipx auto-installed a different version, and then notified me that installed the version that I was initially trying to install. Looks like there are constraints on the package to prevent future Python installations from running them, which I did not realize when installing, nor did pipx convey that to me.
