### ISSUE TITLE
VSCode - Changing from Pylance to Jedi causes Language Server to crash & not come back until switching back to Pylance

### ISSUE THREAD

**Issue by hlafaille** [pappasam/jedi-language-server#273]
Excuse me if this isn't the correct repo, but this is the only thing keeping me from switching from PyCharm and it's very strange why it doesn't work.

On a fresh project, fresh installation of VSCode straight from Microsoft & Debian 12 Bookworm, switching from Pylance to Jedi yields this error:

```
2023-07-05 16:48:43.995 [info] [Error - 4:48:43 PM] Sending notification workspace/didChangeConfiguration failed.
2023-07-05 16:48:43.996 [info] Error: Starting server failed
	at S.$start (/home/hunter/.vscode/extensions/ms-python.python-2023.10.1/out/client/extension.js:2:2058760)
	at async S.sendNotification (/home/hunter/.vscode/extensions/ms-python.python-2023.10.1/out/client/extension.js:2:2044727)
2023-07-05 16:48:43.996 [info] [Error - 4:48:43 PM] Sending notification workspace/didChangeConfiguration failed
2023-07-05 16:48:43.996 [info] Error: Starting server failed
	at S.$start (/home/hunter/.vscode/extensions/ms-python.python-2023.10.1/out/client/extension.js:2:2058760)
	at async S.sendNotification (/home/hunter/.vscode/extensions/ms-python.python-2023.10.1/out/client/extension.js:2:2044727)
```

**Comment by pappasam** [comment]
@hlafaille if you close VSCode and re-open, does it start working? We don't currently support `workspace/didChangeConfiguration`, but that's should not be a problem if you restart vscode

**Comment by hlafaille** [comment]
> @hlafaille if you close VSCode and re-open, does it start working? We don't currently support `workspace/didChangeConfiguration`, but that's should not be a problem if you restart vscode

That is correct, restarting VSCode after changing to Jedi fixes the issue. Can't believe I didn't try this lol. Thank you.
