### ISSUE TITLE
Jedi Language server doesn’t support Python 3.13

### ISSUE THREAD

**Issue by Openstreetmapler** [pappasam/jedi-language-server#329]
In the [Jedi changelog](https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst), it is mentioned that Python 3.12 and 3.13 **are supported**.

> ## 0.19.2 (2024-11-10)
> 
> * Python 3.13 support
> 
> ## 0.19.1 (2023-10-02)
> 
> * Python 3.12 support (Thanks Peter!)

However, in my VSCodium installation on macOS 12, the Jedi language server **does NOT support Python 3.13**:

```python
2024-12-30 17:33:09.070 [info] ERROR:pygls.protocol:Failed to handle request 9 textDocument/documentSymbol DocumentSymbolParams(text_document=TextDocumentIdentifier(uri=<the file I am working on>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/jedi/cache.py", line 110, in wrapper
    return dct[key]
           ~~~^^^^^
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/parso/grammar.py", line 252, in load_grammar
    return _loaded_grammars[path]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: '~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/parso/python/grammar313.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/parso/grammar.py", line 255, in load_grammar
    with open(path) as f:
         ~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/parso/python/grammar313.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 435, in document_symbol
    jedi_script = jedi_utils.script(server.project, document)
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ~~~~~~~~~~~~~~^
        project, environment=environment, script_path=self.path
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/jedi/inference/__init__.py", line 91, in __init__
    self.grammar = environment.get_grammar()
                   ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/jedi/cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/jedi/api/environment.py", line 37, in get_grammar
    return parso.load_grammar(version=version_string)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-oss/extensions/ms-python.python-2024.4.1-universal/python_files/lib/jedilsp/parso/grammar.py", line 264, in load_grammar
    raise NotImplementedError(message)
NotImplementedError: Python version 3.13 is currently not supported.
```

Please update Jedi Language Server to the November 2024 version of Jedi!

**Comment by davidhalter** [comment]
What's your version of parso?

**Comment by Openstreetmapler** [comment]
> What's your version of parso? It feels like you should probably just upgrade your dependencies.

Where do I find the parso version? How can I upgrade its dependencies? I need a walktrough for this!

**Comment by Openstreetmapler** [comment]
> how to upgrade vscode extensions is a question for vscode, not here

As my VSCodium Python extension is already at the latest version, the idea …

> that this project should bump its minimum `jedi` requirement to 0.19.2 - as that is the first version that asserted python 3.13 support

… should be executed!

**Comment by pappasam** [comment]
Addressed in latest release: https://github.com/pappasam/jedi-language-server/releases/tag/v0.43.0
