### ISSUE TITLE
Add support for workspace/didChangeConfiguration notification

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#58]
Add support for this notification: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeConfiguration

Currently I get this error when it is sent.
```
Failed to handle notification workspace/didChangeConfiguration
Traceback (most recent call last):
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 279, in _get_handler
    return self.fm.builtin_features[feature_name]
KeyError: 'workspace/didChangeConfiguration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 282, in _get_handler
    return self.fm.features[feature_name]
KeyError: 'workspace/didChangeConfiguration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 306, in _handle_notification
    handler = self._get_handler(method_name)
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 284, in _get_handler
    raise JsonRpcMethodNotFound.of(feature_name)
pygls.exceptions.JsonRpcMethodNotFound
```

**Comment by krassowski** [comment]
Seconded, this also stretches jupyterlab integration

**Comment by pappasam** [comment]
@krassowski @karthiknadig Please try out this PR and let me know if if resolve the issue for you. We can figure out how / whether to support configuration updates for a running server later, that might take a lot more time than suppressing this error.

<https://github.com/pappasam/jedi-language-server/pull/59>

**Comment by karthiknadig** [comment]
@pappasam that worked for me. Thanks.
