### ISSUE TITLE
CodeAction fails in some cases

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#62]
Repro code:
```py
def func_efdbemfh(x):
    return x == 0


def factorial(x):
    if func_efdbemfh(x) or x == 1:
        return 1
    return x * factorial(x - 1)
```

This should probably go on jedi.

![image](https://user-images.githubusercontent.com/3840081/107006270-bdd21c00-6745-11eb-8647-5aeefe742245.png)

```
[Trace - 11:55:53 PM] Sending request 'textDocument/codeAction - (24)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/GIT/repro/lsptest/tests/test_math2.py"
    },
    "range": {
        "start": {
            "line": 7,
            "character": 31
        },
        "end": {
            "line": 7,
            "character": 31
        }
    },
    "context": {
        "diagnostics": []
    }
}


Failed to handle request 24 textDocument/codeAction Object(textDocument=Object(uri='file:///c%3A/GIT/repro/lsptest/tests/test_math2.py'), range=Object(start=Object(line=7, character=31), end=Object(line=7, character=31)), context=Object(diagnostics=[]))
Traceback (most recent call last):
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 324, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 249, in _execute_request
    self._send_response(msg_id, handler(params))
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi_language_server\server.py", line 468, in code_action
    extract_function_refactoring = jedi_script.extract_function(
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\helpers.py", line 488, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\__init__.py", line 661, in extract_function
    return extract_function(
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\refactoring\extract.py", line 244, in extract_function
    first, second = _split_prefix_at(after_leaf, until_pos[0])
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\refactoring\extract.py", line 148, in _split_prefix_at
    second_line_count = leaf.start_pos[0] - until_line
AttributeError: 'NoneType' object has no attribute 'start_pos'
[Trace - 11:55:53 PM] Received response 'textDocument/codeAction - (24)' in 7ms. Request failed: AttributeError: 'NoneType' object has no attribute 'start_pos' (-32602).
Error data: "{'traceback': ['  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\pygls\\\\protocol.py\", line 324, in _handle_request\\n    self._execute_request(msg_id, handler, params)\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\pygls\\\\protocol.py\", line 249, in _execute_request\\n    self._send_response(msg_id, handler(params))\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi_language_server\\\\server.py\", line 468, in code_action\\n    extract_function_refactoring = jedi_script.extract_function(\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\helpers.py\", line 488, in wrapper\\n    return func(self, line, column, *args, **kwargs)\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\__init__.py\", line 661, in extract_function\\n    return extract_function(\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\refactoring\\\\extract.py\", line 244, in extract_function\\n    first, second = _split_prefix_at(after_leaf, until_pos[0])\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\refactoring\\\\extract.py\", line 148, in _split_prefix_at\\n    second_line_count = leaf.start_pos[0] - until_line\\n']}"


[Error - 11:55:53 PM] Request textDocument/codeAction failed.
  Message: AttributeError: 'NoneType' object has no attribute 'start_pos'
  Code: -32602 
{'traceback': ['  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\pygls\\protocol.py", line 324, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\pygls\\protocol.py", line 249, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi_language_server\\server.py", line 468, in code_action\n    extract_function_refactoring = jedi_script.extract_function(\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\helpers.py", line 488, in wrapper\n    return func(self, line, column, *args, **kwargs)\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\__init__.py", line 661, in extract_function\n    return extract_function(\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\refactoring\\extract.py", line 244, in extract_function\n    first, second = _split_prefix_at(after_leaf, until_pos[0])\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\refactoring\\extract.py", line 148, in _split_prefix_at\n    second_line_count = leaf.start_pos[0] - until_line\n']}
```

![image](https://user-images.githubusercontent.com/3840081/107005992-5b791b80-6745-11eb-8a9c-cadde4d0087b.png)
```
[Trace - 11:59:46 PM] Sending request 'textDocument/codeAction - (5)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/GIT/repro/lsptest/tests/test_math2.py"
    },
    "range": {
        "start": {
            "line": 5,
            "character": 23
        },
        "end": {
            "line": 5,
            "character": 23
        }
    },
    "context": {
        "diagnostics": []
    }
}


Failed to handle request 5 textDocument/codeAction Object(textDocument=Object(uri='file:///c%3A/GIT/repro/lsptest/tests/test_math2.py'), range=Object(start=Object(line=5, character=23), end=Object(line=5, character=23)), context=Object(diagnostics=[]))
Traceback (most recent call last):
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 324, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\pygls\protocol.py", line 249, in _execute_request
    self._send_response(msg_id, handler(params))
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi_language_server\server.py", line 446, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\helpers.py", line 488, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\__init__.py", line 614, in extract_variable
    return extract_variable(
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\refactoring\extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\refactoring\extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "c:\GIT\s p\vscode-python\pythonFiles\lib\python\jedi\api\refactoring\extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
IndexError: list index out of range
[Trace - 11:59:46 PM] Received response 'textDocument/codeAction - (5)' in 10ms. Request failed: IndexError: list index out of range (-32602).
Error data: "{'traceback': ['  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\pygls\\\\protocol.py\", line 324, in _handle_request\\n    self._execute_request(msg_id, handler, params)\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\pygls\\\\protocol.py\", line 249, in _execute_request\\n    self._send_response(msg_id, handler(params))\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi_language_server\\\\server.py\", line 446, in code_action\\n    extract_variable_refactoring = jedi_script.extract_variable(\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\helpers.py\", line 488, in wrapper\\n    return func(self, line, column, *args, **kwargs)\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\__init__.py\", line 614, in extract_variable\\n    return extract_variable(\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\refactoring\\\\extract.py\", line 19, in extract_variable\\n    nodes = _find_nodes(module_node, pos, until_pos)\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\refactoring\\\\extract.py\", line 87, in _find_nodes\\n    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)\\n', '  File \"c:\\\\GIT\\\\s p\\\\vscode-python\\\\pythonFiles\\\\lib\\\\python\\\\jedi\\\\api\\\\refactoring\\\\extract.py\", line 198, in _remove_unwanted_expression_nodes\\n    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)\\n']}"


[Error - 11:59:46 PM] Request textDocument/codeAction failed.
  Message: IndexError: list index out of range
  Code: -32602 
{'traceback': ['  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\pygls\\protocol.py", line 324, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\pygls\\protocol.py", line 249, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi_language_server\\server.py", line 446, in code_action\n    extract_variable_refactoring = jedi_script.extract_variable(\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\helpers.py", line 488, in wrapper\n    return func(self, line, column, *args, **kwargs)\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\__init__.py", line 614, in extract_variable\n    return extract_variable(\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\refactoring\\extract.py", line 19, in extract_variable\n    nodes = _find_nodes(module_node, pos, until_pos)\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\refactoring\\extract.py", line 87, in _find_nodes\n    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)\n', '  File "c:\\GIT\\s p\\vscode-python\\pythonFiles\\lib\\python\\jedi\\api\\refactoring\\extract.py", line 198, in _remove_unwanted_expression_nodes\n    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)\n']}
```

**Comment by pappasam** [comment]
@karthiknadig if possible, would you be able to verify (using the latest master) that the issues identified have been resolved for vscode? They were automatically closed by my merge, but I'm happy to re-open if they're not resolved. Issues:

- https://github.com/pappasam/jedi-language-server/issues/60
- https://github.com/pappasam/jedi-language-server/issues/61
- https://github.com/pappasam/jedi-language-server/issues/62

**Comment by karthiknadig** [comment]
@pappasam Thanks for the changes. The fix from you end helps, but this has to be fixed in `pygls`. The reasons is, any fields that is optional should be removed. In CodeAction response if the `command` field or the `diagnostics` field are left `None` then the code action does not show up. Looks like `pygls`, will fix this, but it will be a breaking change.

To solve this generically as a work around we are doing this: https://github.com/microsoft/vscode-python/pull/15329/files
