### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by s1913388** [pappasam/jedi-language-server#67]
In jupyter lab, the following error occationally occurs:
```python
Failed to handle request 648 textDocument/documentHighlight
Traceback (most recent call last):
  File "/Users/macbook/.pyenv/versions/3.8.7/lib/python3.8/site-packages/pygls/protocol.py", line 324, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/Users/macbook/.pyenv/versions/3.8.7/lib/python3.8/site-packages/pygls/protocol.py", line 249, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/Users/macbook/.pyenv/versions/3.8.7/lib/python3.8/site-packages/jedi_language_server/server.py", line 268, in highlight
    jedi_lines = jedi_utils.line_column(jedi_script, params.position)
  File "/Users/macbook/.pyenv/versions/3.8.7/lib/python3.8/site-packages/jedi_language_server/jedi_utils.py", line 205, in line_column
    line_length = len(lines[position.line])
IndexError: list index out of range
```
jedi-langauge-server=0.23.1

**Comment by pappasam** [comment]
Dang, I'm sorry this happens! Would you be able to provide me an example script where the error occurs for you? If I'm able to reproduce the issue on my end, I'll have an easier time helping resolve this.

**Comment by pappasam** [comment]
Should be resolved in https://github.com/pappasam/jedi-language-server/commit/2641846bbcc46e3e9f918b3bfd23bfae418a17fc
