### ISSUE TITLE
ValueError: `column` parameter (-1) is not in a valid range

### ISSUE THREAD

**Issue by Yevgnen** [pappasam/jedi-language-server#74]
Hi, 

I'm using [lsp-jedi](https://github.com/fredcamps/lsp-jedi) in Emacs. I notice that when the cursor is placed at the end of a Python file (which is usually a blank line), the LSP server keeps printing errors like below

```
Failed to handle request 1761 textDocument/documentHighlight Object(textDocument=Object(uri='file:///Users/user/git/pastebin/test.py'), position=Object(line=3, character=0))
Traceback (most recent call last):
  File "/Users/user/.local/pipx/venvs/jedi-language-server/lib/python3.9/site-packages/pygls/protocol.py", line 324, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/Users/user/.local/pipx/venvs/jedi-language-server/lib/python3.9/site-packages/pygls/protocol.py", line 249, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/Users/user/.local/pipx/venvs/jedi-language-server/lib/python3.9/site-packages/jedi_language_server/server.py", line 269, in highlight
    names = jedi_script.get_references(**jedi_lines, scope="file")
  File "/Users/user/.local/pipx/venvs/jedi-language-server/lib/python3.9/site-packages/jedi/api/helpers.py", line 485, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (-1) is not in a valid range (0-0) for line 4 ('').
```

<img width="727" alt="Screen Shot 2021-02-19 at 11 02 34 AM" src="https://user-images.githubusercontent.com/16749790/108451561-00e1d280-72a2-11eb-9958-679f429b8ab5.png">

Is this a server side issue? Thanks.

**Comment by pappasam** [comment]
Yep, this is a server side issue! Thanks for pointing out!
